# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/dark-glich/Pytorch-Practice/blob/master/Main.ipynb
"""

import torch 
import numpy as np

"""# Tensors
Tensors in pytorch are very similar to numpy arrays except that tensors can run on GPUs.tensors are used to encode the inputs and outputs of a model, as well as the model’s parameters.
"""

# Initializing a Tensor
# From Data
data = [[1,3],[2,4]]
tensor = torch.tensor(data)
print(tensor)

# From Numpy Array
array = np.array([1,2,3])
tensor = torch.tensor(array)
print(tensor)

# From another Tensor
tensor1 = torch.tensor([[1,2],[3,4]], dtype=torch.int8)
tensor2 = torch.ones_like(tensor1) # retains the properties of tensor1
print(tensor2)

# With random or constant values:
ones_tensor = torch.ones((2,3)) # tensor with 1s
random_tensor = torch.rand((2,2)) # tensor with random values
print(ones_tensor)
print(random_tensor)

"""### Attributes of a Tensor
Tensor attributes describe their shape, datatype, and the device on which they are stored.
"""

tensor = torch.tensor([[2,4],[1,3]])
print(tensor.dtype) # Datatype of tensor
print(tensor.shape) # Shape of the tensor
print(tensor.device) # Location where tensor is stored